/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd;

/**
 *
 * @author noemi
 */
public class MeuPainel extends javax.swing.JPanel {

    /**
     * Creates new form MeuPainel
     */
    public MeuPainel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        btnConcatenar = new javax.swing.JToggleButton();
        lblNome = new java.awt.Label();
        lblSobreNome = new java.awt.Label();
        txtNome = new java.awt.TextField();
        txtSobrenome = new java.awt.TextField();
        txtConcatenado = new java.awt.TextField();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("jMenu2");

        jInternalFrame2.setVisible(true);
        jInternalFrame2.getContentPane().setLayout(null);

        btnConcatenar.setText("Concatenar");
        btnConcatenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConcatenarMouseClicked(evt);
            }
        });
        btnConcatenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcatenarActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(btnConcatenar);
        btnConcatenar.setBounds(190, 120, 89, 23);

        lblNome.setText("Nome");
        jInternalFrame2.getContentPane().add(lblNome);
        lblNome.setBounds(10, 20, 38, 20);

        lblSobreNome.setText("Sobrenome");
        jInternalFrame2.getContentPane().add(lblSobreNome);
        lblSobreNome.setBounds(10, 60, 90, 20);
        jInternalFrame2.getContentPane().add(txtNome);
        txtNome.setBounds(100, 20, 200, 20);
        jInternalFrame2.getContentPane().add(txtSobrenome);
        txtSobrenome.setBounds(100, 70, 200, 20);
        jInternalFrame2.getContentPane().add(txtConcatenado);
        txtConcatenado.setBounds(20, 170, 210, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jInternalFrame2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConcatenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcatenarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConcatenarActionPerformed

    private void btnConcatenarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConcatenarMouseClicked
         String nome = this.txtNome.getText();
         String sobreNome = this.txtSobrenome.getText();
         
         String concatenacao =  nome +sobreNome; 
         this.txtConcatenado.setText(concatenacao);
    }//GEN-LAST:event_btnConcatenarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnConcatenar;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private java.awt.Label lblNome;
    private java.awt.Label lblSobreNome;
    private java.awt.TextField txtConcatenado;
    private java.awt.TextField txtNome;
    private java.awt.TextField txtSobrenome;
    // End of variables declaration//GEN-END:variables
}
